### ISSUE TITLE
Bugs with plugin unloading

### ISSUE THREAD

**Issue by dexsper** [rube200/Oxide.Ext.DllLoader#1]
Sometimes strange things happen when reloading a plugin. The unloaded plugin can erase variables from its own class but in a new plugin instance. As if Init hook is called before Unload hook on reloading
PluginReference is very often lost on reloading

**Comment by rube200** [comment]
Does you last pr #2 resolve any of this reports?

**Comment by dexsper** [comment]
> Does you last pr #2 resolve any of this reports?

No, but it's important for you to realize that what I'm talking about here too often breaks plugins, when reloading they stop referring to each other sometimes they have different contexts + there is a feature of oxide that when unloading a plugin the instance is not destroyed, which creates problems if you try to Dispose for something in Unloading
Init and Unload can overlap or be called in a strange order

**Comment by rube200** [comment]
This should be fixed with 1.2.1 release
